### ISSUE TITLE
Save to mysql database.

### ISSUE THREAD

**Issue by dipito31** [drichard/mindmaps#36]
Hi,

I was wondering whether it is possible to save the data of the mindmap in a mysql database.
Also is it possible to directly export the image rather than having to right click and then save it.

Thanks a lot and keep up the good work.

**Comment by mckaygerhard** [comment]
mysql its poor in scalar, owncloud are and app for deploy for utsage reasons.. if this app cannot use with large scalar databases (such like postgres or oracle) don make sense..
