### ISSUE TITLE
"Save to file" doesn't work?

### ISSUE THREAD

**Issue by Wizmann** [drichard/mindmaps#40]
There is no response when I click the "Save to file" button.

Is that a bug?

**Comment by feluxe** [comment]
I have the same issue.

**Comment by JonathanCedrim** [comment]
for who is using, http://app.mindmapmaker.org/. 
Apparently and the new version

**Comment by Bbully** [comment]
Solved! Enable _ShockWave Flash_ in your browser and save to file working.

**Comment by drichard** [comment]
Duplicate of #60.
