### ISSUE TITLE
OwnCloud app

### ISSUE THREAD

**Issue by hitam4450** [drichard/mindmaps#47]
Hi, I like your idea of a mind mapping app very much, since I do work with mind maps in every day projects.
However, i love to see it as an Owncloud app as well or tightly integrated.  Any possibility of achievement?
https://apps.owncloud.com/i
regards, hitam4450

**Comment by rigid** [comment]
:+1:

**Comment by hitam4450** [comment]
HI, any time frame / Schedule available for first Version / trial??

regards, hitam4450
