### ISSUE TITLE
Collaboration, Freemind compatibility -> planned features?

### ISSUE THREAD

**Issue by sDaniel** [drichard/mindmaps#5]
Great work, looks really neat!

I was wondering if you consider adding these features or if you would accept code in this direction?

**Comment by nikolas-n** [comment]
A freemind import/export feature would be fantastic...

**Comment by trond7** [comment]
This does not need to be that difficult.
There are several projects handling converting freemind to other formats.
The most common approach is to use xslt from freemind XML to json.
e.g.:
https://github.com/tohagan/freemind-to-json
Several D3 project support freemind already
e.g.
http://bl.ocks.org/jdarling/2d4e84460d5f5df9c0ff
