### ISSUE TITLE
save on computer doesnt work

### ISSUE THREAD

**Issue by petrk94** [drichard/mindmaps#60]
Hello,

I have install it and it really works, but unfortunately, when I try to save the mindmap on my computer, the save button need flash. But Flash is not longer supported. Is here any solution?
![mindmaps](https://cloud.githubusercontent.com/assets/19719052/24707541/47ae0516-1a14-11e7-86e7-097bbf19943e.PNG)

**Comment by drichard** [comment]
Yeah, I just verified that. I will fix that soon.

**Comment by lgg** [comment]
@drichard ping

**Comment by lgg** [comment]
Fixed in: https://github.com/lgg/mindmaps

**Comment by petrk94** [comment]
@lgg is the issue now finally fixed?

**Comment by lgg** [comment]
@petrk94 in my fork - yes. https://github.com/lgg/mindmaps

Also you can check it yourself online: https://lgg.github.io/mindmaps/

I'm planning to develop my fork separately, so won't create Pull Request.

**Comment by drichard** [comment]
Fixed now. Using the same approach as @lgg. Unfortunately, that means you can't select the filename anymore but it's better than depending on flash.

**Comment by petrk94** [comment]
@drichard how you mean that?
Why the file name cant be changed?
If the save dialog popup appear, than I can change the file name.
Currently its good so 👍

**Comment by lgg** [comment]
@petrk94 there is no save dialog. File only downloaded on your PC and that's all.

**Comment by petrk94** [comment]
@lgg cant verify that, see the screenshot, there is the save dialog appear after click "save" in "to file"
I use Google Chrome 59.0.3071.115
![mindmap](https://user-images.githubusercontent.com/19719052/28281293-dfe5b618-6b26-11e7-9c47-efcd4b6ae006.PNG)

**Comment by lgg** [comment]
@petrk94 last Chrome 0o
![image](https://user-images.githubusercontent.com/12018713/28281579-4761f816-6b30-11e7-8730-93dab8f21051.png)

**Comment by petrk94** [comment]
@lgg hmm thats weird, which OS are you using?
Im using Windows 10 

@drichard what you think about this?

**Comment by lgg** [comment]
@petrk94 win7 x64

**Comment by petrk94** [comment]
@lgg 
Ok, I have setup a Win7 x64 Virtual Machine on my Win 10 host and tried the following.
Open https://lgg.github.io/mindmaps/ in:

- Chrome - Version: 59.0.3071.115
- Opera - Version: 46.0.2597.39
- Firefox - Version:  54.0.1 
- Internet Explorer (not that someone care about it, but just for fun ;) ) - Version: 8.0.7601.17514 (After win7 clean install)
- Internet Explorer - Version: 11.0.9600.17843 (after manually installation)

Results:
- Chrome 59 - works, by saving it download the file directly, without asking  for rename the file
- Opera 46 - works, by saving it download the file directly, without asking for rename the file
- Firefox 54 - Version:  works, by saving it appear a window how to handle the file, without asking for rename the file
- Internet Explorer 8 - doesnt work, only mindmap head appear
- Internet Explorer 11 - works, by saving it download the file directly, without asking for rename the file

As you can see, I think the issue is related to Windows 7, due the tests show that all browsers get only the name, but dont allow to rename the file which get saved.
See Screenshots:
**Chrome 59**
![win7_chrome](https://user-images.githubusercontent.com/19719052/28454527-e469fee2-6dfb-11e7-92b6-a7a728512770.PNG)

**Opera 46**
![win7_opera](https://user-images.githubusercontent.com/19719052/28454545-f42305c2-6dfb-11e7-9117-713a41cddf9b.PNG)

**Firefox 54**
![win7_firefox](https://user-images.githubusercontent.com/19719052/28454598-1e53deb6-6dfc-11e7-8e8a-0698286e0cc9.PNG)

**Internet Explorer 8** (sorry for the german stuff, it means that some content could not been read, in this case the script which I have highlightend )
![win7_ie8](https://user-images.githubusercontent.com/19719052/28456644-55d11640-6e03-11e7-93d9-527e508ebbe1.PNG)

**Internet Explorer 11**
![win7_ie11](https://user-images.githubusercontent.com/19719052/28456698-78c46b98-6e03-11e7-8f3e-f5160e7dd17d.PNG)

**Comment by lgg** [comment]
@petrk94 wow, great work! Thank for investigating it. I will try to find how to fix it.
