### ISSUE TITLE
Problems running self-hosted mindmaps

### ISSUE THREAD

**Issue by csgnyc** [drichard/mindmaps#63]
In the instructions on how to how to host mindmaps, it says "All you need is a web server for static files. Copy all files from /bin into your web directory and launch the app with index.html."  The problem is that in the downloaded version of mindmaps I don't see a file called index.html.  (there are index.html files in some of the subfolders, but I don't think these are the ones that run the program)  Any idea how to fix?

**Comment by drichard** [comment]
Where did you download your version from?

**Comment by csgnyc** [comment]
I used the download .zip option on https://github.com/drichard/mindmaps.

**Comment by csgnyc** [comment]
Never mind.  I'm not all that used to github, but the fork at https://github.com/lgg/mindmaps had "Installation steps" specifying how to download.  You may want to copy those instructions for other github newbies.
