### ISSUE TITLE
Why contentEditable doesn't work ?

### ISSUE THREAD

**Issue by floriandaniel** [drichard/mindmaps#66]
We are students, working on the project FreeMindMaps. In order to improve it, we have to add an editable field, so we need to set the HTML attribute "contenteditable" to true. But when we implement it, the editable field doesn't work (html attribute contenteditable is in the code). 
Do you have an idea of what's the problem ? maybe "interference" between events, or not ?
Thanks.

**Comment by drichard** [comment]
Sorry, I can't help you with that.
