### ISSUE TITLE
filepicker.io API v0 is no more

### ISSUE THREAD

**Issue by EthraZa** [drichard/mindmaps#68]
Save to the cloud is not working anymore.
Looks like the API calls needs to be updated.

***
I was looking for a mind map software and this is by far the best, and is OSS! Thank you for this.

**Comment by drichard** [comment]
Yeah, I'll be fixing this soon or potentially remove the filepicker functionality entirely.

**Comment by drichard** [comment]
I've relased a fix for filepicker! check out www.mindmaps.app for a new version :)
