### ISSUE TITLE
Feature Request: UI: Add `delete node` action for mouse

### ISSUE THREAD

**Issue by DarkTrick** [drichard/mindmaps#98]
Currently I see no way of removing a node by mouse - except of Edit -> Cut.

Suggestion: Add a possibility to easily delete a node (perhaps a trashbox icon next `link` icon)

![image](https://user-images.githubusercontent.com/46980694/115848056-6f880b80-a45e-11eb-9cf6-5419afd1e9ed.png)

**Comment by drichard** [comment]
Thanks for your feature request but I think you are using a different version of the app that someone else made. Have a look here for more info: https://github.com/drichard/mindmaps/issues/91.

**Comment by DarkTrick** [comment]
Darn! That's kind of annoying! Especially given, that you did a really great job and they seem to steal it. 
I also just read your PSA in your README. I'm sad to hear that, but thank you for bringing it this far! I'll close the report.
